Create roles for server
mixanemca/pdns-api pull request #10
Opened 2021-11-03 18:18 UTC by small-jeeper

2021-11-08 13:57 UTC, nemca commented on internal/app/api/app.go
> +	v12 "github.com/mixanemca/pdns-api/internal/app/common/handler/v1"
Может commonV1 вместо v12?

2021-11-08 13:57 UTC, nemca commented on internal/app/config/config.go
> +	ROLE_AUTH   = "authority"
ROLE_API = "api"

2021-11-08 18:51 UTC, small-jeeper commented on internal/app/api/app.go
> +	v12 "github.com/mixanemca/pdns-api/internal/app/common/handler/v1"
Да чет затупил)

2021-11-08 18:52 UTC, small-jeeper commented on internal/app/config/config.go
> +	ROLE_AUTH   = "authority"
поправил)

2021-11-08 18:53 UTC, small-jeeper commented on internal/app/api/app.go
> +	v12 "github.com/mixanemca/pdns-api/internal/app/common/handler/v1"
поправил

2021-11-09 10:37 UTC, nemca requested changes

2021-11-09 10:37 UTC, nemca commented on internal/app/config/config.go
> +	ServerRole     string         `mapstructure:"server-role"`
Я выше уже добавлял поле Role

2021-11-09 18:57 UTC, small-jeeper commented on internal/app/config/config.go
> +	ServerRole     string         `mapstructure:"server-role"`
Удалил=)

2021-11-09 19:47 UTC, merged